artifact_uri: file:///home/claude/debutanizer-mlops/mlflow_store/488774607404464506/dee37a6f00f349d49a4b759d5eca1a0b/artifacts
end_time: 1781962613793
entry_point_name: ''
experiment_id: '488774607404464506'
lifecycle_stage: active
run_id: dee37a6f00f349d49a4b759d5eca1a0b
run_name: initial_training_v1
source_name: ''
source_type: 4
source_version: ''
start_time: 1781962600312
status: 3
tags: []
user_id: root
