aliases: {}
creation_timestamp: 1781962571219
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1781962613773
name: debutanizer-soft-sensor
workspace: default
